import type { User, Project, ParentTask, SubTask, Activity } from "./types"

export const users: User[] = [
  {
    id: "1",
    name: "Ahmet Yılmaz",
    email: "ahmet@spms.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "manager",
  },
  {
    id: "2",
    name: "Elif Demir",
    email: "elif@spms.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "member",
  },
  {
    id: "3",
    name: "Mehmet Kaya",
    email: "mehmet@spms.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "member",
  },
  {
    id: "4",
    name: "Zeynep Akar",
    email: "zeynep@spms.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "member",
  },
  { id: "5", name: "Can Öztürk", email: "can@spms.com", avatar: "/placeholder.svg?height=40&width=40", role: "member" },
]

export const projects: Project[] = [
  {
    id: "1",
    name: "E-Commerce Platform",
    key: "ECOM",
    description: "Building a modern e-commerce platform",
    methodology: "scrum",
    lead: users[0],
    startDate: "2024-01-15",
    endDate: "2024-06-30",
    progress: 68,
  },
  {
    id: "2",
    name: "Mobile Banking App",
    key: "BANK",
    description: "Secure mobile banking application",
    methodology: "kanban",
    lead: users[0],
    startDate: "2024-02-01",
    endDate: "2024-08-15",
    progress: 45,
  },
  {
    id: "3",
    name: "HR Management System",
    key: "HRMS",
    description: "Internal HR management tool",
    methodology: "waterfall",
    lead: users[3],
    startDate: "2024-03-01",
    endDate: "2024-12-31",
    progress: 25,
  },
]

export const subTasks: SubTask[] = [
  {
    id: "st1",
    key: "ECOM-102",
    title: "Design product card component",
    description: "Create reusable product card with image, price, and add to cart button",
    status: "done",
    priority: "high",
    assignee: users[1],
    points: 3,
    parentTaskId: "t1",
    createdAt: "2024-01-20",
    updatedAt: "2024-01-25",
    dueDate: "2024-01-28",
  },
  {
    id: "st2",
    key: "ECOM-103",
    title: "Implement product filtering",
    description: "Add category, price range, and brand filters",
    status: "in-progress",
    priority: "medium",
    assignee: users[2],
    points: 5,
    parentTaskId: "t1",
    createdAt: "2024-01-22",
    updatedAt: "2024-02-01",
    dueDate: "2024-02-05",
  },
  {
    id: "st3",
    key: "ECOM-104",
    title: "Add pagination",
    description: "Implement infinite scroll or pagination for product list",
    status: "todo",
    priority: "low",
    assignee: null,
    points: 2,
    parentTaskId: "t1",
    createdAt: "2024-01-25",
    updatedAt: "2024-01-25",
    dueDate: "2024-02-10",
  },
  {
    id: "st4",
    key: "ECOM-106",
    title: "Cart item quantity update",
    description: "Allow users to update item quantities in cart",
    status: "in-progress",
    priority: "high",
    assignee: users[2],
    points: 3,
    parentTaskId: "t2",
    createdAt: "2024-01-28",
    updatedAt: "2024-02-02",
    dueDate: "2024-02-08",
  },
  {
    id: "st5",
    key: "ECOM-107",
    title: "Remove item from cart",
    description: "Implement remove functionality with confirmation",
    status: "done",
    priority: "medium",
    assignee: users[4],
    points: 2,
    parentTaskId: "t2",
    createdAt: "2024-01-28",
    updatedAt: "2024-02-01",
    dueDate: "2024-02-05",
  },
]

export const parentTasks: ParentTask[] = [
  {
    id: "t1",
    key: "ECOM-101",
    title: "Product Listing Page",
    description:
      "Build the main product listing page with filtering, sorting, and search capabilities. This is a critical feature for the e-commerce platform launch.",
    status: "in-progress",
    priority: "critical",
    assignee: users[1],
    reporter: users[0],
    points: 13,
    projectId: "1",
    project: projects[0],
    subTasks: subTasks.filter((st) => st.parentTaskId === "t1"),
    createdAt: "2024-01-18",
    updatedAt: "2024-02-01",
    dueDate: "2024-02-15",
    isRecurring: false,
    loggedTime: 24,
    estimatedTime: 40,
    labels: ["frontend", "ux", "high-priority"],
  },
  {
    id: "t2",
    key: "ECOM-105",
    title: "Shopping Cart Module",
    description:
      "Implement full shopping cart functionality including add, remove, update quantities, and persist cart state.",
    status: "in-progress",
    priority: "high",
    assignee: users[2],
    reporter: users[0],
    points: 8,
    projectId: "1",
    project: projects[0],
    subTasks: subTasks.filter((st) => st.parentTaskId === "t2"),
    createdAt: "2024-01-25",
    updatedAt: "2024-02-02",
    dueDate: "2024-02-20",
    isRecurring: false,
    loggedTime: 16,
    estimatedTime: 32,
    labels: ["frontend", "state-management"],
  },
  {
    id: "t3",
    key: "BANK-101",
    title: "User Authentication Flow",
    description: "Implement secure login with biometric authentication and 2FA support.",
    status: "todo",
    priority: "critical",
    assignee: users[4],
    reporter: users[0],
    points: 21,
    projectId: "2",
    project: projects[1],
    subTasks: [],
    createdAt: "2024-02-01",
    updatedAt: "2024-02-01",
    dueDate: "2024-03-01",
    isRecurring: false,
    loggedTime: 0,
    estimatedTime: 60,
    labels: ["security", "backend", "mobile"],
  },
  {
    id: "t4",
    key: "HRMS-101",
    title: "Employee Directory",
    description: "Build employee directory with search, filters, and org chart view.",
    status: "done",
    priority: "medium",
    assignee: users[3],
    reporter: users[3],
    points: 8,
    projectId: "3",
    project: projects[2],
    subTasks: [],
    createdAt: "2024-03-05",
    updatedAt: "2024-03-20",
    dueDate: "2024-03-25",
    isRecurring: false,
    loggedTime: 32,
    estimatedTime: 32,
    labels: ["frontend", "database"],
  },
]

export const activities: Activity[] = [
  {
    id: "a1",
    type: "comment",
    user: users[1],
    content: "Updated the product card design based on feedback. Ready for review.",
    timestamp: "2024-02-01T14:30:00",
    taskId: "t1",
  },
  {
    id: "a2",
    type: "status_change",
    user: users[2],
    content: 'Changed status from "Todo" to "In Progress"',
    timestamp: "2024-02-01T10:15:00",
    taskId: "t1",
  },
  {
    id: "a3",
    type: "work_log",
    user: users[1],
    content: "Logged 4 hours on design implementation",
    timestamp: "2024-01-31T17:00:00",
    taskId: "t1",
  },
  {
    id: "a4",
    type: "assignment",
    user: users[0],
    content: "Assigned this task to Elif Demir",
    timestamp: "2024-01-20T09:00:00",
    taskId: "t1",
  },
]

export const currentUser = users[0]
